### ISSUE TITLE
File permissions problem don't result in errors

### ISSUE THREAD

**Issue by MurphyMc** [AbePralle/Rogue#30]
Try compiling some Rogue code into a directory for which you don't have permissions.  It says, e.g., that it wrote the .cpp, but there's no .cpp.  I'd guess the same thing happens if you just open a file and try writing into it.  Not sure what the exact best behavior here is.  Probably just an exception when attempting to open the file.  But almost surely it's not just silent failure.

I can take a look at this in a week or two if I'm not beaten to it.

**Comment by AbePralle** [comment]
Fixed - FileReader() and FileWriter() initializers now throw an IOError if the specified file cannot be opened for any reason.
